const GET_EVENTS_REQUEST = "GET_EVENTS_REQUEST";
const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";
const GET_EVENTS_FAILURE = "GET_EVENTS_FAILURE";

const GET_POPULAR_EVENTS_REQUEST = "GET_POPULAR_EVENTS_REQUEST";
const GET_POPULAR_EVENTS_SUCCESS = "GET_POPULAR_EVENTS_SUCCESS";
const GET_POPULAR_EVENTS_FAILURE = "GET_POPULAR_EVENTS_FAILURE";


export {
    GET_EVENTS_FAILURE,
    GET_EVENTS_SUCCESS,
    GET_EVENTS_REQUEST,
    GET_POPULAR_EVENTS_REQUEST,
    GET_POPULAR_EVENTS_SUCCESS,
    GET_POPULAR_EVENTS_FAILURE
}