const GET_VENUES_REQUEST = "GET_VENUES_REQUEST";
const GET_VENUES_SUCCESS = "GET_VENUES_SUCCESS";
const GET_VENUES_FAILURE = "GET_VENUES_FAILURE";

export {
    GET_VENUES_REQUEST,
    GET_VENUES_FAILURE,
    GET_VENUES_SUCCESS
}